#!/usr/bin/env bash
# App catalog: Arrmate
APP_NAME="arrmate"
APP_DESCRIPTION="AI-powered management interface for Sonarr, Radarr, and Lidarr — control your media stack with natural language"
APP_CATEGORY="management"
APP_PORT_VAR="ARRMATE_PORT"
APP_DEFAULT_HOST_PORT="8000"
APP_SERVICE_PORT="8000"
APP_DEFAULT_SUBDOMAIN="arrmate"
APP_AUTH="tinyauth"
APP_PROFILES="management,all"
APP_IMAGE="techbutton/arrmate:latest"
APP_COMPOSE_FILE="compose/{HOSTNAME}/arrmate.yml"
APP_APPDATA_DIR="appdata/arrmate"
APP_REQUIRES_VOLUMES="appdata"
APP_NOTES="Arrmate uses an LLM backend (Ollama, OpenAI, or Anthropic) to translate natural language into Sonarr/Radarr/Lidarr API calls. Set LLM_PROVIDER and API keys in your .env file after install."
