services:
  # Actual Budget - Personal Finance Manager
  # https://github.com/actualbudget/actual-server
  actual:
    image: actualbudget/actual-server:latest
    container_name: actual
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["productivity", "all"]
    networks:
      - default
    ports:
      - "$ACTUAL_PORT:5006"
    volumes:
      - $DOCKERDIR/appdata/actual:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
    # DOCKER-LABELS-PLACEHOLDER
