services:
  # Audiobookshelf - Audiobook & Podcast Server
  # https://github.com/advplyr/audiobookshelf
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - default
    ports:
      - "$ABS_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/audiobookshelf:/config
      - $DOCKERDIR/appdata/audiobookshelf/metadata:/metadata
      - $AUDIOBOOKS_DIR:/audiobooks
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER
