services:
  # Baïkal - CalDAV and CardDAV Server
  # https://github.com/sabre-io/Baikal
  baikal:
    image: ckulka/baikal:nginx
    container_name: baikal
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["productivity", "all"]
    networks:
      - default
    ports:
      - "$BAIKAL_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/baikal/config:/var/www/baikal/config
      - $DOCKERDIR/appdata/baikal/Specific:/var/www/baikal/Specific
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
    # DOCKER-LABELS-PLACEHOLDER
