services:
  # Calibre-Web - E-book Library
  # https://github.com/linuxserver/docker-calibre-web
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - default
    ports:
      - "$CALIBREWEB_PORT:8083"
    volumes:
      - $DOCKERDIR/appdata/calibre-web:/config
      # Map your existing Calibre library (must contain metadata.db):
      # - /path/to/calibre/library:/books
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DOCKER_MODS: "linuxserver/mods:universal-calibre"  # optional: enables ebook conversion
    # DOCKER-LABELS-PLACEHOLDER
