services:
  # Calibre - E-Book Management Suite
  # https://github.com/kovidgoyal/calibre
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - default
    ports:
      - "$CALIBRE_PORT:8080"
      # Optional: Calibre Content Server for e-reader clients
      # - "8081:8081"
    volumes:
      - $DOCKERDIR/appdata/calibre:/config
      # Map your Calibre library:
      # - /path/to/calibre-library:/config/Calibre Library
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER
