services:
  # DokuWiki - File-Based Wiki
  # https://github.com/dokuwiki/dokuwiki
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["documents", "all"]
    networks:
      - default
    ports:
      - "$DOKUWIKI_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/dokuwiki:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER
