services:
  # Dozzle Agent - Remote Log Aggregation Agent
  # https://github.com/amir20/dozzle
  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle-agent
    command: agent
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["monitoring", "all"]
    networks:
      - default
    ports:
      - "$DOZZLE_AGENT_PORT:7007"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
    # DOCKER-LABELS-PLACEHOLDER
