services:
  # FlareSolverr - Cloudflare Bypass Proxy
  # https://github.com/FlareSolverr/FlareSolverr
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["arr", "all"]
    networks:
      - default
    ports:
      - "$FLARESOLVERR_PORT:8191"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      LOG_LEVEL: info
    # DOCKER-LABELS-PLACEHOLDER
