services:
  # FreshRSS - RSS Feed Aggregator
  # https://github.com/FreshRSS/FreshRSS
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["productivity", "all"]
    networks:
      - default
    ports:
      - "$FRESHRSS_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/freshrss/data:/var/www/FreshRSS/data
      - $DOCKERDIR/appdata/freshrss/extensions:/var/www/FreshRSS/extensions
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      CRON_MIN: "1,31"
    # DOCKER-LABELS-PLACEHOLDER
