services:
  # GameVault - Self-Hosted Game Library
  # https://github.com/Phalcode/gamevault-backend
  # NOTE: Licensed CC BY-NC-SA 4.0 — non-commercial use only
  gamevault:
    image: ghcr.io/phalcode/gamevault-backend:latest
    container_name: gamevault
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - default
    ports:
      - "$GAMEVAULT_PORT:8080"
    volumes:
      - $DOCKERDIR/appdata/gamevault:/media
      # Map your games directory:
      # - /path/to/games:/files:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - gamevault-db
    environment:
      TZ: $TZ
      DB_SYSTEM: POSTGRESQL
      DB_HOST: gamevault-db
      DB_PORT: 5432
      DB_USERNAME: gamevault
      DB_PASSWORD: ${GAMEVAULT_DB_PASSWORD:-changeme123}
      DB_DATABASE: gamevault
    # DOCKER-LABELS-PLACEHOLDER

  # PostgreSQL for GameVault
  gamevault-db:
    image: postgres:16-alpine
    container_name: gamevault-db
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - default
    volumes:
      - gamevault-pg-data:/var/lib/postgresql/data
    environment:
      TZ: $TZ
      POSTGRES_USER: gamevault
      POSTGRES_PASSWORD: ${GAMEVAULT_DB_PASSWORD:-changeme123}
      POSTGRES_DB: gamevault

volumes:
  gamevault-pg-data:
