services:
  # Grocy - Household Management
  # https://github.com/grocy/grocy
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["productivity", "all"]
    networks:
      - default
    ports:
      - "$GROCY_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/grocy:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER
