services:
  # Heimdall - Application Dashboard
  # https://github.com/linuxserver/Heimdall
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["dashboard", "all"]
    networks:
      - default
    ports:
      - "$HEIMDALL_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/heimdall:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER
