services:
  # Jellyfin - Media Server (open-source Plex alternative)
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - default
    user: $PUID:$PGID
    devices:
      - /dev/dri:/dev/dri # for hardware transcoding
    ports:
      - "$JELLYFIN_PORT:8096"
      # - "8920:8920" # Emby also uses same port if running both
    environment:
      UMASK_SET: 022
      TZ: $TZ
    volumes:
      - $DOCKERDIR/appdata/jellyfin:/config
      - $DOWNLOADSDIR:/data/downloads
      - $MOVIES_DIR:/data/movies
      - $TV_DIR:/data/tv
      - $MUSIC_DIR:/data/music
      - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    # DOCKER-LABELS-PLACEHOLDER
