services:
  # Kavita - Manga, Comics & E-book Server
  # https://github.com/Kareadita/Kavita
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - default
    ports:
      - "$KAVITA_PORT:5000"
    volumes:
      - $DOCKERDIR/appdata/kavita:/kavita/config
      - $BOOKS_DIR:/books
      - $COMICS_DIR:/comics
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
    # DOCKER-LABELS-PLACEHOLDER
