services:
  # Lidarr - Music Management
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "starr", "all"]
    networks:
      - default
    ports:
      - "$LIDARR_PORT:8686"
    volumes:
      - $DOCKERDIR/appdata/lidarr:/config
      - $MUSIC_DIR:/data/music
      - $DOWNLOADSDIR:/data/downloads
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      LIDARR__Auth__ApiKey: $LIDARR_API_KEY
    # DOCKER-LABELS-PLACEHOLDER
