services:
  # MQTTX Web - MQTT Debugging Client
  # https://github.com/emqx/MQTTX
  mqttx:
    image: emqx/mqttx-web:latest
    container_name: mqttx
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["automation", "all"]
    networks:
      - default
    ports:
      - "$MQTTX_PORT:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
    # DOCKER-LABELS-PLACEHOLDER
