services:
  # Netdata - Real-Time System Monitoring
  # https://github.com/netdata/netdata
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    restart: unless-stopped
    profiles: ["monitoring", "all"]
    networks:
      - default
    ports:
      - "$NETDATA_PORT:19999"
    volumes:
      - $DOCKERDIR/appdata/netdata/config:/etc/netdata
      - $DOCKERDIR/appdata/netdata/lib:/var/lib/netdata
      - $DOCKERDIR/appdata/netdata/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      NETDATA_CLAIM_TOKEN: ""
      NETDATA_CLAIM_URL: ""
    # DOCKER-LABELS-PLACEHOLDER
