services:
  # Node Exporter - Prometheus Host Metrics Exporter
  # https://github.com/prometheus/node_exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["monitoring", "all"]
    networks:
      - default
    ports:
      - "$NODE_EXPORTER_PORT:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    environment:
      TZ: $TZ
    # DOCKER-LABELS-PLACEHOLDER
