services:
  # Open WebUI - LLM Web Interface
  # https://github.com/open-webui/open-webui
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["ai", "all"]
    networks:
      - default
    ports:
      - "$OPEN_WEBUI_PORT:8080"
    volumes:
      - $DOCKERDIR/appdata/open-webui:/app/backend/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      OLLAMA_BASE_URL: "http://ollama:11434"
      WEBUI_SECRET_KEY: ${OPEN_WEBUI_SECRET:-changeme-use-a-random-string}
    # DOCKER-LABELS-PLACEHOLDER
