services:
  # phpMyAdmin - MySQL/MariaDB Management UI
  # https://github.com/phpmyadmin/phpmyadmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["database", "all"]
    networks:
      - default
    ports:
      - "$PHPMYADMIN_PORT:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PMA_HOST: mariadb
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    # DOCKER-LABELS-PLACEHOLDER
