services:
  # Plex - Media Server
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - default
    ports:
      - "$PLEX_PORT:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    devices:
      - /dev/dri:/dev/dri # for hardware transcoding
    volumes:
      - $DOCKERDIR/appdata/plex:/config
      - $DOWNLOADSDIR:/data/downloads
      - $MOVIES_DIR:/data/movies
      - $TV_DIR:/data/tv
      - $MUSIC_DIR:/data/music
      - /dev/shm:/data/transcode
    environment:
      TZ: $TZ
      HOSTNAME: $PLEX_SERVER_NAME
      PLEX_CLAIM_FILE: /run/secrets/plex_claim
      PLEX_UID: $PUID
      PLEX_GID: $PGID
      ADVERTISE_IP: "http://$SERVER_LAN_IP:32400/,https://plex.$DOMAINNAME_1"
    secrets:
      - plex_claim
    # DOCKER-LABELS-PLACEHOLDER
