services:
  # PrivateBin - Zero-Knowledge Pastebin
  # https://github.com/PrivateBin/PrivateBin
  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    container_name: privatebin
    security_opt:
      - no-new-privileges:true
    read_only: true
    restart: unless-stopped
    profiles: ["productivity", "all"]
    networks:
      - default
    ports:
      - "$PRIVATEBIN_PORT:8080"
    volumes:
      - $DOCKERDIR/appdata/privatebin:/srv/data
      - /etc/localtime:/etc/localtime:ro
    user: "$PUID:$PGID"
    environment:
      TZ: $TZ
    # DOCKER-LABELS-PLACEHOLDER
