services:
  # Smokeping - Network Latency Monitoring
  # https://github.com/oetiker/SmokePing
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["monitoring", "all"]
    networks:
      - default
    ports:
      - "$SMOKEPING_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/smokeping/config:/config
      - $DOCKERDIR/appdata/smokeping/data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER
