services:
  # Speedtest Tracker - Internet Speed Monitor
  # https://github.com/alexjustesen/speedtest-tracker
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["monitoring", "all"]
    networks:
      - default
    ports:
      - "$SPEEDTEST_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/speedtest-tracker:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      APP_KEY: ${SPEEDTEST_APP_KEY:-base64:changeme-generate-with-openssl-rand-base64-32}
      DB_CONNECTION: sqlite
    # DOCKER-LABELS-PLACEHOLDER
