services:
  # TinyAuth - Lightweight SSO for Traefik ForwardAuth
  # https://tinyauth.app/
  tinyauth:
    container_name: tinyauth
    image: ghcr.io/steveiliop56/tinyauth:${TINYAUTH_VERSION_PIN:-v3}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["security", "all"]
    networks:
      - default
      - t3_proxy
    volumes:
      - ${DOCKERDIR}/appdata/tinyauth/users_file:/tinyauth/users_file
    environment:
      - SECRET_FILE=/run/secrets/tinyauth_secret
      - APP_URL=https://auth.${DOMAINNAME_1}
      - USERS_FILE=users_file
      - LOG_LEVEL=0
      - LOGIN_MAX_RETRIES=3
      - LOGIN_TIMEOUT=300
      - DISABLE_CONTINUE=true
    secrets:
      - tinyauth_secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tinyauth-rtr.entrypoints=websecure-internal"
      - "traefik.http.routers.tinyauth-rtr.rule=Host(`auth.${DOMAINNAME_1}`)"
      - "traefik.http.routers.tinyauth-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.tinyauth-rtr.service=tinyauth-svc"
      - "traefik.http.services.tinyauth-svc.loadbalancer.server.port=3000"
    # DOCKER-LABELS-PLACEHOLDER
