services:
  # Vaultwarden - Self-hosted Bitwarden-compatible Password Manager
  # https://github.com/dani-garcia/vaultwarden
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["security", "all"]
    networks:
      - default
    ports:
      - "$VAULTWARDEN_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/vaultwarden:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      DOMAIN: "https://vault.${DOMAINNAME_1}"
      SIGNUPS_ALLOWED: "true"   # Set to false after creating your account
      INVITATIONS_ALLOWED: "true"
      WEBSOCKET_ENABLED: "true"
      LOG_LEVEL: "warn"
    # DOCKER-LABELS-PLACEHOLDER
