services:
  # WikiDocs - Flat-File Markdown Wiki
  # https://github.com/Zavy86/WikiDocs
  wikidocs:
    image: zavy86/wikidocs:latest
    container_name: wikidocs
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["documents", "all"]
    networks:
      - default
    ports:
      - "$WIKIDOCS_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/wikidocs:/datasets
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER
