services:
  # ZeroTier - Software-Defined Networking
  # https://github.com/zerotier/ZeroTierOne
  zerotier:
    image: zerotier/zerotier:latest
    container_name: zerotier
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    profiles: ["network", "all"]
    # host network required for virtual network interface
    network_mode: host
    volumes:
      - $DOCKERDIR/appdata/zerotier:/var/lib/zerotier-one
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
    # Join a network: docker exec zerotier zerotier-cli join <network-id>
    # Authorize the node at: https://my.zerotier.com
    # DOCKER-LABELS-PLACEHOLDER
